export const INDENT_ADD_REQUEST = 'INDENT_ADD_REQUEST'
export const INDENT_ADD_SUCCESS = 'INDENT_ADD_SUCCESS'
export const INDENT_ADD_FAIL = 'INDENT_ADD_FAIL'

export const INDENT_GETALL_REQUEST = 'INDENT_GETALL_REQUEST'
export const INDENT_GETALL_SUCCESS = 'INDENT_GETALL_SUCCESS'
export const INDENT_GETALL_FAIL = 'INDENT_GETALL_FAIL'
export const INDENT_GETALL_RESET = 'INDENT_GETALL_RESET'

export const INDENT_GET_BY_DATE_REQUEST = 'INDENT_GET_BY_DATE_REQUEST'
export const INDENT_GET_BY_DATE_SUCCESS = 'INDENT_GET_BY_DATE_SUCCESS'
export const INDENT_GET_BY_DATE_FAIL = 'INDENT_GET_BY_DATE_FAIL'

export const INDENT_GET_BY_ID_REQUEST = 'INDENT_GET_BY_ID_REQUEST'
export const INDENT_GET_BY_ID_SUCCESS = 'INDENT_GET_BY_ID_SUCCESS'
export const INDENT_GET_BY_ID_FAIL = 'INDENT_GET_BY_ID_FAIL'

export const INDENT_UPDATE_REQUEST = 'INDENT_UPDATE_REQUEST'
export const INDENT_UPDATE_SUCCESS = 'INDENT_UPDATE_SUCCESS'
export const INDENT_UPDATE_FAIL = 'INDENT_UPDATE_FAIL'
