export const INDENT_ADD_REQUEST = 'INDENT_ADD_REQUEST';
export const INDENT_ADD_SUCCESS = 'INDENT_ADD_SUCCESS';
export const INDENT_ADD_FAIL = 'INDENT_ADD_FAIL';

export const INDENT_GETALL_REQUEST = 'INDENT_GETALL_REQUEST'
export const INDENT_GETALL_SUCCESS = 'INDENT_GETALL_SUCCESS'
export const INDENT_GETALL_FAIL = 'INDENT_GETALL_FAIL'