export const ORDER_ADD_REQUEST = 'ORDER_ADD_REQUEST'
export const ORDER_ADD_SUCCESS = 'ORDER_ADD_SUCCESS'
export const ORDER_ADD_FAIL = 'ORDER_ADD_FAIL'

export const ORDER_GET_MINE_REQUEST = 'ORDER_GET_MINE_REQUEST'
export const ORDER_GET_MINE_SUCCESS = 'ORDER_GET_MINE_SUCCESS'
export const ORDER_GET_MINE_FAIL = 'ORDER_GET_MINE_FAIL'

export const ORDER_GET_ALL_REQUEST = 'ORDER_GET_ALL_REQUEST'
export const ORDER_GET_ALL_SUCCESS = 'ORDER_GET_ALL_SUCCESS'
export const ORDER_GET_ALL_FAIL = 'ORDER_GET_ALL_FAIL'